### ISSUE TITLE
"MVPリリース"レビュー依頼

### ISSUE THREAD

**Issue by h-tac** [h-tac/my_portfolio_app_01#85]
### サービス名
自転車空気入れマップ

### サービスURL
https://www.bicycle-air-pump-map.com

**Comment by Tsuchiya2** [comment]
ご提出ありがとうございます。
確認したいことがあるのでご回答もしくは確認をお願いします。

---
（以下README.mdより）
■MVPリリース時
- ユーザーが、空気入れを利用できる施設の場所をアプリに登録し、地図でその座標を表示できるようにする。
- 無料／有料、手動／自動、バルブ形状、営業時間を登録できるようにする。
- 空気入れ貸し出しスポット利用時の感想等を投稿できるようにする。
- スマホでGoogleマップアプリを開き目的地を表示できるようにする。
- ログイン機能、お気に入り機能、登録履歴機能、パスワードリセット機能を実装。
- 地名検索機能を実装。

上記の「 無料／有料、手動／自動、バルブ形状、営業時間を登録できるようにする。」ですが、ログイン後のどの導線から行えるのかが分からなかったため、URLもしくは確認のための手順をコメント欄に記載してください。

**Comment by h-tac** [comment]
トップページのマップ右上に、施設登録ボタンがあります。
わかりやすくポップアップを追加しましたのでご確認お願いします。

**Comment by Tsuchiya2** [comment]
確認できました。LGTMです。
本リリースに向けて引き続き頑張ってください。
